name: Build V-Rising Server Docker Images

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Hardcode the lowercase repository owner name
  REGISTRY_IMAGE: ghcr.io/teriyakidactyl/docker-vrising-server
  BASE_REGISTRY_IMAGE: ghcr.io/teriyakidactyl/docker-steamcmd-server
  # Define the base tags from steamcmd-server to build against
  MATRIX_BASE_TAGS: |
    trixie-20250407-slim_wine-staging-10.5
    bookworm-20250407-slim_wine-staging-10.5
  MATRIX_PLATFORMS: |
    linux/amd64
    linux/arm64

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      base-tags: ${{ steps.set-matrix.outputs.base-tags }}
      platforms: ${{ steps.set-matrix.outputs.platforms }}
    steps:
      - id: set-matrix
        name: Process matrix configurations
        run: |
          BASE_TAGS=$(echo '${{ env.MATRIX_BASE_TAGS }}' | grep -v '^$' | awk '{print "\""$0"\""}' | paste -sd, | awk '{print "["$0"]"}')
          PLATFORMS=$(echo '${{ env.MATRIX_PLATFORMS }}' | grep -v '^$' | awk '{print "\""$0"\""}' | paste -sd, | awk '{print "["$0"]"}')
          echo "base-tags=$BASE_TAGS" >> $GITHUB_OUTPUT
          echo "platforms=$PLATFORMS" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        base_tag: ${{ fromJson(needs.setup.outputs.base-tags) }}
        platform: ${{ fromJson(needs.setup.outputs.platforms) }}
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare tag variables
        id: prep-tags
        run: |
          ARCHITECTURE=$(echo ${{ matrix.platform }} | cut -d'/' -f2)
          echo "ARCHITECTURE=$ARCHITECTURE" >> $GITHUB_ENV
          
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            BRANCH_SUFFIX="_dev"
          else
            BRANCH_SUFFIX=""
          fi
          echo "BRANCH_SUFFIX=$BRANCH_SUFFIX" >> $GITHUB_ENV
          
          # This is the tag for the base image we are pulling from steamcmd-server
          BASE_TAG_FOR_PULL="${{ matrix.base_tag }}${BRANCH_SUFFIX}-${ARCHITECTURE}"
          echo "BASE_TAG_FOR_PULL=$BASE_TAG_FOR_PULL" >> $GITHUB_ENV
          
          # Generate tag parts for the new v-rising image we are building
          # Full tag: trixie-20250407-slim_wine-staging-10.5-amd64
          FULL_TAG="${{ matrix.base_tag }}${BRANCH_SUFFIX}-${ARCHITECTURE}"
          echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV

          # Simple tag: trixie-amd64
          SIMPLE_TAG=$(echo "${{ matrix.base_tag }}" | cut -d'-' -f1)${BRANCH_SUFFIX}-$ARCHITECTURE
          echo "SIMPLE_TAG=$SIMPLE_TAG" >> $GITHUB_ENV

          # Latest tag (only for main branch on default base image)
          if [[ "${{ github.ref_name }}" == "main" && "${{ matrix.base_tag }}" == "trixie-20250407-slim_wine-staging-10.5" ]]; then
            echo "LATEST_ARCH_TAG=latest-$ARCHITECTURE" >> $GITHUB_ENV
          fi
          
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ env.FULL_TAG }}
            type=raw,value=${{ env.SIMPLE_TAG }}
            ${{ env.LATEST_ARCH_TAG != '' && format('type=raw,value={0}', env.LATEST_ARCH_TAG) || '' }}
          labels: |
            org.opencontainers.image.title=V-Rising Server Docker Image
            org.opencontainers.image.description=Docker image for V-Rising dedicated server using Wine.
            org.opencontainers.image.vendor=TeriyakiDactyl
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_TAG=${{ env.BASE_TAG_FOR_PULL }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha,scope=${{ matrix.base_tag }}-${{ matrix.platform }}
          cache-to: type=gha,scope=${{ matrix.base_tag }}-${{ matrix.platform }},mode=max

  create-manifest:
    needs: [setup, build]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        base_tag: ${{ fromJson(needs.setup.outputs.base-tags) }}
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Generate manifest tag names
        id: manifest-tags
        run: |
          BASE_DIST=$(echo "${{ matrix.base_tag }}" | cut -d'-' -f1)
          
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "SIMPLE_MANIFEST_TAG=$BASE_DIST" >> $GITHUB_ENV
            echo "FULL_MANIFEST_TAG=${{ matrix.base_tag }}" >> $GITHUB_ENV
            if [[ "${{ matrix.base_tag }}" == "trixie-20250407-slim_wine-staging-10.5" ]]; then
              echo "LATEST_TAG=latest" >> $GITHUB_ENV
              echo "HAS_LATEST_TAG=true" >> $GITHUB_ENV
            fi
          else
            echo "SIMPLE_MANIFEST_TAG=${BASE_DIST}_dev" >> $GITHUB_ENV
            echo "FULL_MANIFEST_TAG=${{ matrix.base_tag }}_dev" >> $GITHUB_ENV
            echo "HAS_LATEST_TAG=false" >> $GITHUB_ENV
          fi
      
      - name: Create and push multi-architecture manifests
        run: |
          BRANCH_SUFFIX=""
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            BRANCH_SUFFIX="_dev"
          fi

          # Create simple manifest tag (e.g., "trixie" or "trixie_dev")
          SIMPLE_TAG_BASE=$(echo "${{ matrix.base_tag }}" | cut -d'-' -f1)
          docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }}:${{ env.SIMPLE_MANIFEST_TAG }} \
            ${{ env.REGISTRY_IMAGE }}:${SIMPLE_TAG_BASE}${BRANCH_SUFFIX}-amd64 \
            ${{ env.REGISTRY_IMAGE }}:${SIMPLE_TAG_BASE}${BRANCH_SUFFIX}-arm64
          echo "::notice::Successfully created manifest for ${{ env.REGISTRY_IMAGE }}:${{ env.SIMPLE_MANIFEST_TAG }}"

          # Create full manifest tag (e.g., "trixie-20250407-slim_wine-staging-10.5")
          docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }}:${{ env.FULL_MANIFEST_TAG }} \
            ${{ env.REGISTRY_IMAGE }}:${{ matrix.base_tag }}${BRANCH_SUFFIX}-amd64 \
            ${{ env.REGISTRY_IMAGE }}:${{ matrix.base_tag }}${BRANCH_SUFFIX}-arm64
          echo "::notice::Successfully created manifest for ${{ env.REGISTRY_IMAGE }}:${{ env.FULL_MANIFEST_TAG }}"

          if [[ "${{ env.HAS_LATEST_TAG }}" == "true" ]]; then
            docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }}:latest \
              ${{ env.REGISTRY_IMAGE }}:latest-amd64 \
              ${{ env.REGISTRY_IMAGE }}:latest-arm64
            echo "::notice::Successfully created 'latest' multi-architecture manifest"
          fi

